#! /bin/sh

sxhkd &

setxkbmap -option ctrl:nocaps # caps -> ctrl
xcape -e 'Shift_R=Shift_L|0;Shift_L=Shift_L|9' -t 300 # space cadet shift

~/etc/polybar/launch.sh
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         2
bspc config window_gap          10

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true


